from colorama import Fore 
import os
import sys 
import time  
import tqdm 
numbers=list(range(1,101,1))
Loading_ascii_art=['''
                    
                    ....
                    .... 
                    ....
                    ....
                     .... 
                      ....
                      ....
                      ....
                      ....
                      ....
                      ....
                      ....
                      ....
                      ....
                      ....
                      ....
                      ....
                      ....
                      ....
                      ....''','''
                      ....
                       ....
                        ....
                         .... 
                          ....
                           ....
                            ....
                             ....                          
                             ....
                             ....
                             ....
                             ....
                             ....
                             ....
                             ....
                             ....''',
                       '''  
                            ....
                           ....
                          ....
                          ....
                          ....
                          ....
                          ....
                          ....
                          ....
                          ....
                          ....
                          ....
                          ....
                          ....
                           ....''',
                        ''' 
                            ....
                            ....
                            ....
                            ....
                            ....
                            ....
                            ....
                            ....
                            ....
                            ....
                            ....
                            ....
                            ....
                            ....
                            ....
                            ....''',
                         '''
                           ....
                          ....
                         ....
                        ....
                       ....
                      ....
                     ....''','''
                     ....
                     ....
                     ....
                     ....
                     ....
                     ....
                     ....
                     ....
                     ....
                     ....
                     ....
                     ....
                     ....
                     ....
                    ....
                   ....
                  ....
                 ....
                ....
                |  |
               |    |
                | .|
                \  /
                 \/''']
for n in range(20):
 for x in Loading_ascii_art[:-1]:
    sys.stdout.flush()
    time.sleep(0.1)
    sys.stdout.write(f'{Fore.GREEN}{x}')
else:
    time.sleep(1)
    print(f'{Loading_ascii_art[-1]}')
    time.sleep(1)
    for nim in tqdm.tqdm(numbers,colour='GREEN',desc='Loading message...',ncols=100):
        time.sleep(0.01)
    else:
        time.sleep(1)
        message='You saw a snake...'
        for text in message:
            sys.stdout.flush()
            time.sleep(0.1)
            sys.stdout.write(f'{Fore.RED}{text}')
        else:
            time.sleep(1)
            os.system('cls')
            time.sleep(1)
            sys.exit(f'{Fore.RESET}')